### PR TITLE
Feat:Showcase in Chat VC

### LINKED ISSUE #553: ShowCase in Chat VC.
**Actual Behaviour**

No showcase for first time user

**Expected Behaviour**

Should be present for better UI/UX 

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by baquer**
Fixes #553 

Changes: Add showcase in Chat VC.

Screenshots for the change: 

Screenshot 2019-04-21 at 3 04 23 AM

### CODE REVIEW

**Comment by baquer** [comment]
@chashmeetsingh, @jogendra, Please review the PR.

**Comment by chashmeetsingh** [comment]
Wouldn't it be a good idea to remove the black overlay over the buttons?

**Comment by baquer** [comment]
> Wouldn't it be a good idea to remove the black overlay over the buttons?

@chashmeetsingh, actually the black overlay over the Susi button is due to the Impact or overloading of a showcase on skill button, Here is the difference.

Screenshot 2019-05-11 at 11 56 46 PM

Screenshot 2019-05-11 at 11 56 51 PM

**Comment by baquer** [comment]
> Can you please resolve the conflicts so that I can review the PR?

Done @jogendra

**Pull request merged**
