### PR TITLE
Feat: Swift 5 Migration

### LINKED ISSUE #539: Migration to Swift 5.0

### PR DESCRIPTION
**Pull request by baquer**
Fixes #539 

Changes: Conversion to swift 5

Screenshots for the change: 

N/A

### CODE REVIEW

**Comment by baquer** [comment]
@chashmeetsingh, @jogendra, Please Review the PR.

**Comment by baquer** [comment]
@jogendra, after migrating to swift 5.0, the project is not building due to JI pod failure, as JI pod is not updated for swift 5.0.
I will look into it.

**Comment by baquer** [comment]
@jogendra, the project is building now by manually making changes in JI and Readabilitykit pod files. Any idea of how to make a permanent change in these pods?

**Comment by jogendra** [comment]
@baquer If the pod is not in use, remove the Pod or find the good alternative. Otherwise, make a pull request to made changes in pod. The other thing we could do is make a fork to our org and make changes and use it but this is not the good way and I am not sure we will fork other repo in our org. @mariobehling could we do that?

**Comment by baquer** [comment]
> @baquer If the pod is not in use, remove the Pod or find the good alternative. Otherwise, make a pull request to made changes in pod. The other thing we could do is make a fork to our org and make changes and use it but this is not the good way and I am not sure we will fork other repo in our org. @mariobehling could we do that?

@jogendra, I think Changing outdated pod to the latest pod is a better and long term solution.

**Comment by baquer** [comment]
I will make a PR soon for the new pods.

**Comment by baquer** [comment]
@jogendra the pods which I mentioned earlier are now updated to the latest version, now the project is building successfully without any errors. Please check it in your local repository too.
So should I change the pods or leave it here itself?

**Comment by jogendra** [comment]
@baquer The circle-ci test is failing. PR cannot be reviewed/merge till it pass all the test. Please first pass all the test, test it well from your side then ping here.

**Comment by baquer** [comment]
> @baquer The circle-ci test is failing. PR cannot be reviewed/merge till it pass all the test. Please first pass all the test, test it well from your side then ping here.

Okay, @jogendra I will try to fix the failing issue of circle ci.

**Comment by jogendra** [comment]
Closing the PR due to inactivity. Feel free to open a new PR.

**Pull request closed without merging**
