### PR TITLE
Feat: Feedback by latest timestamp

### LINKED ISSUE #520: Show skill feedback by latest timestamp
**Actual Behaviour**

Currently feedback are displaying in older timestamp.

**Expected Behaviour**

Make feedback display by latest timestamp.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by baquer**
Fixes #520 

Changes: show feedback by latest timestamp

Screenshots for the change: 

screenshot 2019-02-21 at 3 04 02 am

### CODE REVIEW

**Comment by baquer** [comment]
@chashmeetsingh , @jogendra , please review the PR.

**Comment by chashmeetsingh** [comment]
Why not do something like this:

```
var feedbacks: [Feedback]? {
        get {
            return feedbacks?.sorted(by: {$0.timeStamp > $1.timeStamp})
        }
        didSet {
            feedbackDisplayTableView.reloadData()
        }
    }
```

**Comment by baquer** [comment]
@jogendra , here is the SS.

screenshot 2019-02-21 at 7 53 51 pm

**Comment by jogendra** [comment]
@baquer I would suggest you to use method suggested by @chashmeetsingh

**Comment by baquer** [comment]
> @baquer I would suggest you to use method suggested by @chashmeetsingh

@jogendra , i tried with the getter, setter method , which @chashmeetsingh  suggested , but , when i put the code in getter , its make a recursive call with this warning "All paths through this function will call itself" and the app is getting terminated by giving this error "EXC_BAD_ACCESS (code=2, address=0x7ffedfda1fb8)"

**Comment by jogendra** [comment]
@baquer okay! Approving your PR.

**Comment by chashmeetsingh** [comment]
Oh, ok. But why is `reloadData()` called  before the elements are sorted.

**Comment by baquer** [comment]
> Oh, ok. But why is `reloadData()` called before the elements are sorted.

@chashmeetsingh , thanks for pointing this , it's my mistake 😁 , will fix this .

**Comment by chashmeetsingh** [comment]
Please squash your commits.

**Comment by jogendra** [comment]
I am squashing and merging!

**Pull request merged**
