### PR TITLE
Fix: Set title label in skill detail VC

### LINKED ISSUE #521: show title label in skillDetailVC
**Actual Behaviour**

Currently title label is missing.

**Expected Behaviour**

Title should be present.

**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by baquer**
Fixes #521 

Changes: set title in skill detail view controller

### CODE REVIEW

**Comment by baquer** [comment]
@chashmeetsingh , @jogendra  , please review the PR.

**Comment by jogendra** [comment]
@baquer Please add a screenshot for UI changes as mentioned in contributing guidelines.

**Comment by baquer** [comment]
> @baquer Please add a screenshot for UI changes as mentioned in contributing guidelines.

screenshot 2019-02-21 at 7 49 18 pm

**Comment by chashmeetsingh** [comment]
I think @jogendra is right. There would be a repetition.

**Comment by jogendra** [comment]
@baquer @chashmeetsingh closing it for now

**Pull request closed without merging**
