### PR TITLE
Integrated gravatar for users in feedback section

### LINKED ISSUE #406: Integrate Gravatar for users in feedback section
**Actual Behaviour**

Currently, user's initials are shown in the feedback section.

**Expected Behaviour**

Show the user's avatar.

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by imjog**
Fixes #406, Parent issue #399 

Changes:
- Added gravatar in the feedback section of **Skill Detail** Screen
- Added gravatar in **See All Feedback** screen
- Increases the height of `FeedbackDisplayCell`

Corresponding SUSI Android PR: https://github.com/fossasia/susi_android/pull/1645

Screenshots for the change: 
<table>
<tr>
<td>Skill Detail Screen</td>
<td>See All Feedback</td>
</tr>
<tr>
<td>

</td>
<td>

</td></tr>
</table>

### CODE REVIEW

**Comment by imjog** [comment]
@arundhati24 Please review!

**Comment by imjog** [comment]
@akshatnitd Please review!

**Comment by imjog** [comment]
@akshatnitd this is because of the screenshot was taken from the simulator. The divider is showing correctly.

**Comment by imjog** [comment]
looking into failing codacy.

**Comment by akshatnitd** [comment]
@imjog Great :+1:

**Pull request merged**
