### PR TITLE
Replaced PieChart with BarChart for five star ratings UI on Skill Detail screen

### LINKED ISSUE #328: Replace PieChart with BarChart for five star ratings UI on Skill Detail screen
**Actual Behaviour**

Currently, PieChart UI is using for five-star rating system on skill detail screen. (In the screenshot below)

**Expected Behaviour**

PieChart should replace with BarChart to make five star rating UI consistent with SUSI Android. (In the screenshot below)

**Steps to reproduce it**

Go to Skill Listing < Skill Detail

**Screenshots of the issue**

Current iOS UI:

Current Android UI:

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by imjog**
Fixes #328 

Changes: Replaced PieChart with BarChart for five-star rating UI on Skill Detail screen

Screenshots for the change: 
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td>

</td>
<td>

</td></tr>
</table>

### CODE REVIEW

**Comment by imjog** [comment]
@chashmeetsingh @arundhati24 Please review and give your suggestions.

**Comment by arundhati24** [comment]
@imjog Please remove the positive and negative ratings data from the skill details screen. We no longer need to show this rating here.

**Comment by arundhati24** [comment]
Could you please add the bar labels? For instance, if there were 2 ratings in total out of which one was a 5 star and another one was a 4 star, then it means 50% users rated it at 5 stars and 50% at 4 stars. So the bars could bear the values on the horizontal axis that they correspond to. the same has been implemented in Android app. You can have a look at it. 

You can also check this image for an example : 

screenshot_1527708775


On a side note, I would be formatting the bar labels soon to move them outside the bars so as to avoid their overlapping with the axis labels, if possible, after checking the MPAndroidChart library. Also, I would try to replace * with stars if that functionality is supported by the library (need to check).
But, in any case there would be labels to display the values, which are missing in the screenshot provided by you.

**Comment by arundhati24** [comment]
@imjog I would like to know if we need to add the SUBMIT button? As discussed during Android/iOS walkthrough, we need to implement it without a SUBMIT button if possible. I don't know if that is possible in iOS but in android I have not added this button. I have simply attached a OnRatingBarChangeListener to the rating bar, which detects the change in rating as soon as the user interacts with the rating bar. Please let me know whether this button has to be kept or not so that we have similar designs in both the apps.
API integration for sending user ratings is still in progress in Android app while the skill details chart displays the actual ratings from the server.

**Comment by arundhati24** [comment]
Also, are these colors from some standard color palette? I had used some random colors as per my choice, but I was suggested to use lighter colors. I then tried to use colors similar ro those used by Google. You can see those colors in the image above. If, these are some satndard colors being used in iOS apps, then it's okay, else may be you could also use a bit lighter colors.

**Comment by arundhati24** [comment]
The distance between the values and the labels for average rating and total rating could be decreased a bit imho.

**Comment by imjog** [comment]
@arundhati24 thank you for the explanation.
- Regarding displaying total rating for each star in label bar, I have that in mind but I was confused where should I add because as developed in Android there will be a case when 4 stars (eg.any three or four) are very highly rated and one star is very low rated so inside total number of will go half outside the bar and doesn't look good. I will add that to outside as you said you are planning.
- Regarding * in Android app, The star's image I put is not part of the library, it is just a `stackView` that aligned to numbers and rating bars.
- Regarding SUBMIT button, it can be submitted easily without SUBMIT button, I implemented delegate methods that detects whenever the stars change. I only added SUBMIT button to keep it similar to Google Home iOS app which Mario told me to do. I will remove it to make consistent with Android. Also, I am aware of APIs, I am following with Server team for submitting the rating and there is already response coming for skill detail chart.
- Regarding Colors, Yes they are Apple Human Interface guideline color, I posted a link for same in gitter channel. It is good to decrease colors opacity (alpha) to half to make it lighter?
- Regarding distance between vales and their label, I am decreasing it.

**Comment by imjog** [comment]
@arundhati24 @chashmeetsingh Here is updated UI (**EXCEPT:** total number of ratings for each bar. The library I am using does not have this feature, I have to add it. **MPAndroidChart**, the library you are using, is supporting label outside the bar (see Horizontal Bar section). Also, the same library available for iOS too (https://github.com/danielgindi/Charts) but I avoided to use it here because of its big size and we are just using chart one place):
simulator screen shot - iphone 8 - 2018-06-09 at 15 26 56

**Comment by imjog** [comment]
@chashmeetsingh @arundhati24 here is the final UI:
simulator screen shot - iphone 8 - 2018-06-10 at 04 45 42

**Comment by chashmeetsingh** [comment]
Center align the stars and it's title. For the rating part, remove the stars and place them as average rating below 2.5 and for now remove the rating count infront, looks odd.

**Comment by arundhati24** [comment]
@imjog I am also trying to work on the UI part now. 
The above changes look good, but, could you please explain why the number of users has been placed after the star as labels? When the number of users will grow, these numbers will become large and it would appear strange.
As, the UI on skill CMS also has bar shadow, I am also adding it. (The UI which we have been referring to also has bar shadow). That way it would cover the empty space and not make it odd in case the skill has very less number of total ratings.
I too have not been able to place the ratings towards the end of each bar, but yes the library that I have used allows to put the bar entry values on top of the bar. 
Regarding the stars, I am still looking into it already. '*' is just a placeholder for now. I am aware that it does not look good. 😄 
I will be adding a screenshot soon.

**Comment by imjog** [comment]
@arundhati24 The number of users has been placed after the starts because I tried to put after the bar but doesn't look good to me, Also the major reason is library I am using is offering text inside the bar or outside the bar. The library is written in Objective-C, I tried to modify it but doesn't work.
Google is not showing the number of stars for each star bar. Can we skip?
Regarding bar shadow, I can add here too but if there is no spacing between the bars then it will not look like the shadow, it will look like background color which looks very odd. (On the web there is spacing between bars)

**Comment by arundhati24** [comment]
@imjog Here is the UI that i have made finally. 
screenshot_1528713298

**Comment by imjog** [comment]
@chashmeetsingh @arundhati24 Here is the final UI:
final

**Comment by chashmeetsingh** [comment]
@imjog decrease the size of the grey stars. Rest looks good.

**Comment by arundhati24** [comment]
@imjog I agree with @chashmeetsingh . Rest looks good. 😃

**Pull request merged**
