### PR TITLE
displaying chats from bottom to top

### LINKED ISSUE #281: Displaying chats from Bottom to Top
**Actual Behaviour**
Currently there is overlapping of first chat and the button.Chats are displayed from top to bottom.

**Expected Behaviour**

Chats should be displayed from bottom to Top and no overlapping of button and chats should exist.

**Screenshots of the issue**

/root/Downloads/WhatsApp Image 2018-05-01 at 3.39.52 PM.jpeg

**Would you like to work on the issue?**

Yes I would like to work on this issue.

### PR DESCRIPTION
**Pull request by SIMRAN1**
Fixes #281 

Changes: chats are displayed from bottom to top

Screenshots for the change: 
image

### CODE REVIEW

**Comment by SIMRAN1** [comment]
@imjog @chashmeetsingh please review the pr!!

**Comment by chashmeetsingh** [comment]
@SIMRAN1 please add screenshots and possibly a GIF or video so that it can be reviewed easily.

**Comment by SIMRAN1** [comment]
okk @chashmeetsingh I will add scrrenshots or video!

**Comment by SIMRAN1** [comment]
@imjog I have resolved it!

**Comment by SIMRAN1** [comment]
okk @imjog I got the problem now! I will send a fix for it!

**Comment by imjog** [comment]
@SIMRAN1 Follow [this link](https://stackoverflow.com/questions/23715555/configure-uicollectionviewflowlayout-to-layout-rows-from-bottom-to-top/23895000#23895000) may help you.

**Comment by SIMRAN1** [comment]
@imjog Yes I will send a pr in a day . My exams were going on so i was not able to see this issue!

**Comment by SIMRAN1** [comment]
@imjog @chashmeetsingh I have tried many solutions for issue and its not working . @imjog please take this issue for solving . I apologise for inconvenience caused.

**Comment by imjog** [comment]
No problem @SIMRAN1. Please close this PR.

**Pull request closed without merging**
