### PR TITLE
Fix: added a minimum message width

### PR DESCRIPTION
**Pull request by chashmeetsingh**
Fixes issue #115 

Changes: 
- Added min. message width

Screenshots for the change: 
screen shot 2017-06-23 at 12 19 10 pm

### CODE REVIEW

**Comment by chashmeetsingh** [comment]
please review @dynamitechetan @chiragw15 @isuruAb @mayank408 @amitiwary999 @betterclever

**Comment by betterclever** [comment]
@chashmeetsingh The timestamp looks a bit cluttered. How about making them like Google Assistant?

screenshot_20170623-134719

**Comment by chashmeetsingh** [comment]
@betterclever please create another issue for the same?

**Comment by betterclever** [comment]
@chashmeetsingh If we change it, all client must reflect the same.

@chiragw15 @rishiraj824 What is your preference on it or shall we do it later ?

**Comment by chashmeetsingh** [comment]
Yes, that's true.

**Comment by chiragw15** [comment]
@chashmeetsingh @betterclever Please add all UI ideas in this issue https://github.com/fossasia/susi_server/issues/280

**Pull request merged**
