### PR TITLE
Improved the UI of 'Reset Password' screen

### LINKED ISSUE #325: Modify the UI of 'Reset Password' screen
**Actual Behaviour**

UI is not consistent with UI of login, signup and forgot password activity (see in the screenshot below)

**Expected Behaviour**

UI of Reset password screen should be same as login, signup and forgot password screens

**Steps to reproduce it**

Go to 'Settings > Reset password'

**Screenshots of the issue**

simulator screen shot - iphone 8 - 2018-06-07 at 16 37 42

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by imjog**
Fixes #325 

Changes: Implemented new UI for **Reset Password** screen

Screenshots for the change: 
<table>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td>

</td>
<td>

</td></tr>
</table>

### CODE REVIEW

**Comment by imjog** [comment]
@chashmeetsingh @SIMRAN1 Please review!

**Comment by chashmeetsingh** [comment]
@imjog I guess the previous UI looks much cleaner and goes with the app's theme.

**Comment by imjog** [comment]
@chashmeetsingh Yes, the previous UI was good but Mario told me to change the background to white but with white background it was looking odd so I changed similar to Forgot Password and Signup screens.

**Comment by imjog** [comment]
@akshatnitd I have to discuss with @chashmeetsingh if this is needed or not. Will resolve conflicts after that

**Comment by chashmeetsingh** [comment]
@imjog how does the UI on susi android look like? Have the same changes been made there?

**Comment by imjog** [comment]
@chashmeetsingh They changed UI of reset password some days ago. Currently, they are using login screen email to send reset the password and removed reset password screen. They display a message screen, I will do the same.

**Comment by imjog** [comment]
Closing it, will be made a PR soon to make UI similar newly changes UI of SUSI Android

**Pull request closed without merging**
