### PR TITLE
Uses continuous buffer for detection instead of the timer

### LINKED ISSUE #172: Use continuous buffer for detection instead of the timer
**Actual Behaviour**

Currently, a timer calls and detection process happens.

**Expected Behaviour**

There should be no delay in the detection process.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by imjog**
Fixes #172 

Changes: Use continuous buffer for detection instead of the timer
-  Added AudioKit
- Added delegate methods

Screenshots for the change: 
N/A

### CODE REVIEW

**Comment by imjog** [comment]
@chashmeetsingh Please review

**Comment by chashmeetsingh** [comment]
Can you share a video demonstration for this? @imjog

**Comment by imjog** [comment]
Okey @chashmeetsingh

**Comment by imjog** [comment]
Hi @chashmeetsingh Please find the video demonstration for this here: https://youtu.be/S1ry2z0ebmM

**Comment by chashmeetsingh** [comment]
The continuous buffer is for the hotword but in the video I can't see that being used anywhere. @imjog

**Comment by chashmeetsingh** [comment]
Resolve conflicts!

**Comment by imjog** [comment]
@chashmeetsingh Resolved

**Comment by chashmeetsingh** [comment]
Will keep this PR open for the next few days as I do not have a testing device to test this on yet.

**Comment by chashmeetsingh** [comment]
@imjog just tried it out. Looks like the recorder is running but never does the recognition happen.  I tried it with my personalised model, still no recognition. Please look into the issue.

**Comment by imjog** [comment]
@chashmeetsingh  I can't able to figure out where and how this issue happening. Can I close it for now?

**Pull request closed without merging**
