### PR TITLE
feat: load memory from network after login

### PR DESCRIPTION
**Pull request by chashmeetsingh**
Fixes issue #132: retrieve messages from memory after login success

Changes:
- on login, load messages from memory

### CODE REVIEW

**Comment by chashmeetsingh** [comment]
please review @dynamitechetan @chiragw15 @isuruAb @mayank408 @amitiwary999 @betterclever

**Comment by amitiwary999** [comment]
Can I test it on appetizer?

**Comment by chashmeetsingh** [comment]
The free time has been used from that account. I can add a GIF though.

**Comment by chashmeetsingh** [comment]
@amitiwary999 

gif

**Comment by mariobehling** [comment]
Please resolve conflicts.

**Comment by chashmeetsingh** [comment]
done!

**Pull request merged**
