### PR TITLE
Feat: Add resend verification link for the user

### LINKED ISSUE #536: Resend Verification Link in sign up view controller
**Actual Behaviour**

No Resend Verification Link option available on sing up page

**Expected Behaviour**

It should be present if in case the user misses the verification email

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by baquer**
Fixes #536 

Changes: 

1.  Add resend link button
2. Call API for resending the verification link to the user.

Screenshots for the change: 

Screenshot 2019-03-24 at 2 41 06 AM

### CODE REVIEW

**Comment by baquer** [comment]
@chashmeetsingh, @jogendra, Please review the PR.

**Comment by baquer** [comment]
> keep the button small in size and place just below and right side of Sign up button.

@jogendra, There is an Activity Indicator just below the signup button, so can I put Activity Indicator after the resend button? and can you please explain to me about the right side of the signup button?

**Comment by baquer** [comment]
> keep the button small in size and place just below and right side of Sign up button.

Done @jogendra 

Screenshot 2019-04-03 at 11 36 09 PM

**Comment by jogendra** [comment]
@baquer Keep the button right side and make it little smaller.

**Comment by baquer** [comment]
@jogendra 

Is this Okay?

Screenshot 2019-04-04 at 10 54 29 PM

**Comment by jogendra** [comment]
Looks okay to me. I am little bit confused, should we place here to just below email text field. @chashmeetsingh ?

**Comment by chashmeetsingh** [comment]
This place looks fine but shouldn't it be center aligned?

**Comment by baquer** [comment]
> Looks okay to me. I am little bit confused, should we place here to just below email text field. @chashmeetsingh ?

@jogendra, Any update?

**Comment by jogendra** [comment]
There is a problem with the API method.
Simulator Screen Shot - iPhone 8 - 2019-05-24 at 00 33 45

**Comment by baquer** [comment]
> There is a problem with the API method.
> Simulator Screen Shot - iPhone 8 - 2019-05-24 at 00 33 45

@jogendra have you tried it using a new unverified email or the existing email account? because it case of existing email or account it will give server error.

**Comment by baquer** [comment]
@jogendra, at my end it is working fine.

Screenshot 2019-05-24 at 1 17 00 AM

Screenshot_20190524-011717

**Comment by jogendra** [comment]
@baquer Handle the error properly. when the user is already registered and request resend, show them the same, not that problem connecting to the server.

**Comment by baquer** [comment]
> @baquer Handle the error properly. when the user is already registered and request resend, show them the same, not that problem connecting to the server.

Done @jogendra 

Screenshot 2019-06-15 at 12 11 58 AM

**Comment by baquer** [comment]
> Follow https://stackoverflow.com/questions/17703510/dyld-library-not-loaded-reason-image-not-found to fix the lint issue. Other than that, looks good to me.

Will fix the lint issue.

**Comment by jogendra** [comment]
@baquer change 11.2 to 12.2 in https://github.com/fossasia/susi_iOS/blob/master/Scripts/build_for_testing.sh

**Comment by baquer** [comment]
> @baquer change 11.2 to 12.2 in https://github.com/fossasia/susi_iOS/blob/master/Scripts/build_for_testing.sh

doing it.

**Comment by baquer** [comment]
Thanks, @jogendra It's working now 😁

**Comment by jogendra** [comment]
@baquer Yeah finally

@chashmeetsingh please review :)

**Comment by baquer** [comment]
> @baquer Yeah finally
> 
> @chashmeetsingh please review :)

@jogendra Yeah, also I am thinking of fixing this issue in other iOS projects.

**Pull request merged**
