### PR TITLE
thumbs up, thumbs down cannot be changed and fixed feedback not accepting

### LINKED ISSUE #380: Thumbs up or down cannot be changed
The feedback once given on an interaction should not be changeable, otherwise it will cause inconsistencies in the feedback logs that will be used for analysis.

**Would you like to work on the issue?**

No, anyone can assign the issue to himself/herself.

### PR DESCRIPTION
**Pull request by imjog**
Fixes #380, #385 

Changes:
- Remove thumbs up and thumbs after successfully submitted feedback to prevent multiple feedbacks
- Fixed feedback not accepting issue

Screenshots for the change: 
<table>
<tr>
<td>Before feedback (News)</td>
<td>After feedback (News)</td>
</tr>
<tr>
<td>

</td>
<td>

</td></tr>
</table>

### CODE REVIEW

**Comment by imjog** [comment]
@AnupKumarPanwar @batbrain7 please review!

**Comment by imjog** [comment]
@chashmeetsingh It is not checking and will display thumbs up and down again because from server side we don't have any check if the feedback is submitted or not, the same goes to realm database. All we can do is temporary disable thumbs up and down.

**Comment by batbrain7** [comment]
Yes, this is what is happening if we need to permanently reflect this, we have to change the Memory API from the server

**Comment by imjog** [comment]
@batbrain7 I am not sure how memory API can do that because messages don't have any ID associated and also, a anonymous user can submit feedback too.

**Comment by chashmeetsingh** [comment]
IMO the Issue is still now fixed of user is able to provide feedback after he opens the app again.

**Comment by AnupKumarPanwar** [comment]
Yes, thats a tricky part. We are allowing anonymous feedbacks as well as we need to identify the feedbacks uniquely.

**Comment by imjog** [comment]
@chashmeetsingh Web and Android client are also having this temporary feature. For now, can we add this? and in the future when server-side implement this, we will implement here too.

**Comment by mariobehling** [comment]
Ok, let'd iterate on this. Cheers.

**Pull request merged**
