### PR TITLE
Feat: Add Account Section Cell in Setting View Controller.

### LINKED ISSUE #541: Add Account Section Cell in Setting View controller.
**Actual Behaviour**

No account section cell for the account setting

**Expected Behaviour**

It Should be present.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by baquer**
Fixes #541 

Changes: 
1: Add table view cell in setting Vc
2: Show user image and email in the cell

Screenshots for the change: 

Screenshot 2019-03-30 at 11 11 09 PM

### CODE REVIEW

**Comment by baquer** [comment]
@chashmeetsingh, @jogendra, Please review the PR.

**Comment by chashmeetsingh** [comment]
Maybe move reset password and logout to this section as well?

**Comment by baquer** [comment]
Yeah, It's a good idea to place correlated options under the same section. @jogendra what's your view?

**Comment by baquer** [comment]
@chashmeetsingh, @jogendra, here is an updated SS.

Screenshot 2019-04-05 at 11 58 57 PM

**Comment by chashmeetsingh** [comment]
LGTM!

**Pull request merged**
