### PR TITLE
Skip codesigning

### LINKED ISSUE #32: Code signing causes build failure
Code signing being turned on sometimes causes Travis build failures

### PR DESCRIPTION
**Pull request by chashmeetsingh**
Fixes #32: Skips codesigning which causes issues.

### CODE REVIEW

**Comment by mariobehling** [comment]
Which issue?

**Comment by chashmeetsingh** [comment]
Travis build fails due to the code signing some times

**Comment by mariobehling** [comment]
Which issue? Please match issues with PRs. Please follow best practices.

**Comment by mariobehling** [comment]
http://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/#commits

**Pull request merged**
