### PR TITLE
Added .DS_Store files to .gitignore

### LINKED ISSUE #263: Add .DS_Store file to .gitignore
**Actual Behaviour**

Whenever anyone setup project on MacOS. MacOS generate the filename `.DS_Store` which contain custom attributes of its containing folder, such as the position of icons or the choice of a background image. The name is an abbreviation of Desktop Services Store, reflecting its purpose. Read more about `.DS_Store` file [here](https://en.wikipedia.org/wiki/.DS_Store).
Currently, `.DS_Store` file is not added in `.gitignore` file. 

**Expected Behaviour**

`.DS_Store` file should be added to `.gitignore` file. 

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by imjog**
Fixes #263 Added `.DS_Store` files to `.gitignore`

Changes: .gitignore all the .DS_Store files in every folder and subfolder and deleted `.DS_Store` file

### CODE REVIEW

**Comment by chashmeetsingh** [comment]
@imjog adding that way would only ignore file from the root folder but it needs to be done recursively inside all folders. Please make the necessary changes.
Thanks!

**Comment by imjog** [comment]
@chashmeetsingh I read on StackOverflow that this will ignore files for root folders too.
I will add for root folders too in next commit :)

**Comment by imjog** [comment]
@chashmeetsingh can you please tell, why the Codacy is failing?

**Comment by chashmeetsingh** [comment]
Try swiftlint to fix those issues

**Comment by imjog** [comment]
@chashmeetsingh I tried swiftlint and other options but still, Codacy is failing. Also, codacy is not showing issues and warning. I just changes .gitignore file. I can't able to figure out the problem. can you please help me regarding this?

**Comment by chashmeetsingh** [comment]
Have you followed https://stackoverflow.com/a/26454988 ?? Currently it only removes the file from the project root and not the files inside folders.

**Comment by imjog** [comment]
@chashmeetsingh thank you for sharing the link. all checks are passing now.

**Comment by chashmeetsingh** [comment]
Please squash your commits.

**Comment by chashmeetsingh** [comment]
Still 2 commits are present.

**Comment by imjog** [comment]
@chashmeetsingh I have to merge **master** branch into my branch (imjog-patch2), otherwise, it is giving an error and failing the checks. When I fetch and merge **master** branch into **imjog-patch2** from the terminal, the last merge is not showing in commits so can't able to squash them.
screen shot 2018-03-13 at 01 30 02

**Comment by chashmeetsingh** [comment]
For that you need to update the forked repo. Try this: https://stackoverflow.com/a/7244456

**Comment by imjog** [comment]
@chashmeetsingh Now ready to merge! Learned more Git and Linting than code :satisfied:

**Pull request merged**
