### PR TITLE
Adding support for playing youtube video in the app

### LINKED ISSUE #294: Play audio from a Youtube stream
**Expected Behaviour**

When susi returns a audio_play action, the hardware which the user is using must play the given audio source.

**Steps to reproduce it**

Ask susi "open the pod bay door" - https://api.susi.ai/susi/chat.json?q=open+the+pod+bay+door
You will get the following action object:
```
"actions": [
      {
        "type": "audio_play",
        "identifier_type": "youtube",
        "identifier": "7qnd-hdmgfk"
      },
      {
        "language": "en",
        "type": "answer",
        "expression": "I'm sorry, Dave. I'm afraid I can't do that."
      }
    ]
```
or
```
"actions": [
      {
        "type": "video_play",
        "identifier_type": "youtube",
        "identifier": "7qnd-hdmgfk"
      },
      {
        "language": "en",
        "type": "answer",
        "expression": "I'm sorry, Dave. I'm afraid I can't do that."
      }
    ]
```

This means that susi shall do (in that order):
* if "type" is "audio_play": play the audio from the youtube video with the given ID. Use the "identifier_type" to see that the "identifier" object denotes a youtube ID
* if "type" is "video_play": play the video from the youtube video with the given ID. Use the "identifier_type" to see that the "identifier" object denotes a youtube ID
* write out the answer

**Documentation of the audio_play action**

see issue https://github.com/fossasia/susi_linux/issues/117

**Would you like to work on the issue?**

Please let us know if you can work on it or the issue should be assigned to someone else.

### PR DESCRIPTION
**Pull request by imjog**
Fixes #294 

Changes: Added support for playing youtube video in the app
- Implemented support for `video_play` action
- `YouTubePlayer` delegate methods for **auto-playing** video
- Presenting player using `PlayerViewController`

**Video Demonstration**: https://drive.google.com/open?id=17I6tp43pJWfVe4HNmv2ZP8Rt_Vv2hlmo

Screenshots for the change: 
<table>
<tr>
<td>

</td>
<td>

</td></tr>
</table>

### CODE REVIEW

**Comment by imjog** [comment]
@chashmeetsingh I stuck in an issue:
During `video_play` response, `youtubePlayer` is opening which is declared in ChatViewController. If there is already a player, I am removing from `superView`. the issue is whenever user scroll chat screen, `youtubePlayer` is unnecessarily open up. I couldn't be able to resolve it. Do you have any solution in mind? Please help to resolve it.

**Comment by chashmeetsingh** [comment]
@imjog take a look at my implementation that I did: https://github.com/fossasia/susi_iOS/pull/62

**Comment by chashmeetsingh** [comment]
Also, I cloned the project (this branch) there seems to be a compile error, please fix it!

**Comment by imjog** [comment]
@chashmeetsingh Fixing it.

**Comment by imjog** [comment]
@chashmeetsingh Centered `videoPlayer` and resign first responders before opening video.  I think `The video is unavailable` issue from the YouTube side or the player script is not supporting the **Ads** that play just before playing video.
Regarding thumbnails, I added the thumbnails before but whenever we scroll the chat screen, videoPlayer open up. The same issue i was talking about here: https://github.com/fossasia/susi_iOS/pull/372#issuecomment-402983138

**Comment by chashmeetsingh** [comment]
`The video unavailable is not Youtube's issue. Actually, its the pod being used. Check https://github.com/chashmeetsingh/Swift-YouTube-Player/commit/12a86fc8211756253458213c37ad0b11eaeb93a4 I had fixed this last issue last year.

Regarding the issue, I need to view it first, direct me to the commit?

**Comment by imjog** [comment]
@chashmeetsingh I lost the commit code in rebasing. But you can see this issue, ask susi for playing video multiple time and then scroll the chat screen, you will see that youtube player is popping up again and again.

**Comment by imjog** [comment]
@chashmeetsingh Resolve the **The video is unavailable** issue.
simulator screen shot - iphone x - 2018-07-09 at 12 38 38

**Comment by chashmeetsingh** [comment]
@imjog It has something to do with the cell reusability. The `addYotubePlayer` method is called multiple times. Try following the breakpoint approach and find the cause.

**Comment by imjog** [comment]
@chashmeetsingh Please review it now. I created a new youtube player.
I will work Youtube video thumbnail in next PR.

**Comment by imjog** [comment]
@chashmeetsingh I tried different approaches still the issue is there. I tried debugging but able to figure out the problem. Can you please look into it? Or for now, we can add the thumbnail and when user tap thumbnail, we will play youtube video. I will work on Autoplay feature after that.

**Comment by imjog** [comment]
@chashmeetsingh Now, it is working fine. Please review!

**Comment by chashmeetsingh** [comment]
@imjog Nice work! As a next step, can you check if we can dismiss the blackView from the video player after the `X` button is pressed? Currently, we close the video player then tap the blackView to dismiss it.

**Pull request merged**
