### PR TITLE
Anonymize the user email address in Feedback section

### LINKED ISSUE #408: Anonymize the user email address in Feedback section
**Actual Behaviour**

The feedback section currently shows complete email addresses.

**Expected Behaviour**

Anonymize the feedback and only show emails until the @ sign, e.g. "mariobehling@..".

**Screenshots of the issue**
**Current screens:**
<table>
<tr>
<td>Skill Detail Screen</td>
<td>See All Feedback</td>
</tr>
<tr>
<td>

</td>
<td>

</td></tr>
</table>

**Expected:** (Web implemetation)
screen shot 2018-08-10 at 23 54 48

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by imjog**
Fixes #408, Parent issue #399 

Changes: Anonymize the feedback and only show emails until the @ sign, e.g. "mariobehling@...".

Screenshots for the change: 
<table>
<tr>
<td>Skill Detail Screen</td>
<td>See All Feedback</td>
</tr>
<tr>
<td>

</td>
<td>

</td></tr>
</table>

### CODE REVIEW

**Comment by chashmeetsingh** [comment]
Why not do this with the username instead of the provider?

**Comment by imjog** [comment]
@chashmeetsingh username is optional so many of them not set. I am checking if API returns username too and display username.

**Comment by imjog** [comment]
@chashmeetsingh In `getSkillFeedback` API response, we are getting user email only. Here is the sample response:
https://api.susi.ai/cms/getSkillFeedback.json?group=News&language=en&model=general&skill=news
```
{
feedback: [
{
feedback: "Helpful",
email: "imjog24@gmail.com",
timestamp: "2018-07-10 18:17:04.549"
},
{
feedback: "wow",
email: "arundhatigupta2411@gmail.com",
timestamp: "2018-08-01 19:18:16.831"
},
{
feedback: "Cool",
email: "testuserdev1996@gmail.com",
timestamp: "2018-06-25 10:15:53.886"
},
{
feedback: "Nice :)",
email: "gupta.arundhati2411@gmail.com",
timestamp: "2018-06-25 11:34:04.063"
},
{
feedback: "Wow",
email: "coolakshat24@gmail.com",
timestamp: "2018-06-25 13:03:08.639"
},
{
feedback: "Nice.Works well!",
email: "123divyanshu.n.s4@gmail.com",
timestamp: "2018-06-28 21:18:36.659"
},
{
feedback: "Nice This is a great skill",
email: "akjn11@gmail.com",
timestamp: "2018-06-28 21:30:06.403"
},
{
feedback: "Awesome!",
email: "akshatnitd@gmail.com",
timestamp: "2018-07-09 23:01:46.38"
},
{
feedback: "Comes handy",
email: "coolcooder@gmail.com",
timestamp: "2018-07-15 19:10:28.421"
},
{
feedback: "nice!",
email: "anshu.av97@gmail.com",
timestamp: "2018-07-22 07:03:03.641"
},
{
feedback: "Good!",
email: "shivangidwivedi147@gmail.com",
timestamp: "2018-07-22 19:50:41.634"
},
{
feedback: "Test123",
email: "shubhamsuperpro@gmail.com",
timestamp: "2018-07-25 13:32:43.446"
},
{
feedback: "Awesome!!",
email: "suneetbond91@gmail.com",
timestamp: "2018-08-12 20:59:06.866"
}
],
session: {
identity: {
type: "host",
name: "162.158.167.14_6275db14",
anonymous: true
}
},
skill_name: "news",
accepted: true,
message: "Skill feedback fetched"
}
```

**Comment by chashmeetsingh** [comment]
I meant encoding `imjog24@gmail.com` to something like `im***@gm***.com`

**Comment by imjog** [comment]
@chashmeetsingh I followed the way mention here https://github.com/fossasia/susi_skill_cms/issues/1132#issue-341647541. Also, the web and android is following the same. I think the goal is not to anonymize username, the goal is to anonymize their full email address. @akshatnitd Can you please explain?

**Pull request merged**
