### PR TITLE
Handle no network connection

### PR DESCRIPTION
**Pull request by ashishkakkad8**
An indicator should show up whenever the internet connection is down.

Fixes #[230]

Changes: An indicator should show up whenever the internet connection is down.

Screenshots for the change: 

ss 230

### CODE REVIEW

**Comment by ashishkakkad8** [comment]
Please check "Handle no network connection"

**Comment by chashmeetsingh** [comment]
@ashishkakkad8 thanks for the PR.
Can you also handle the enable and disable of the mic button? As well as showing some kind of tap to reload for the skills view? Do the enabling and disabling of the buttons for login/signup/forgot-password views as well.

**Comment by chashmeetsingh** [comment]
@ashishkakkad8 are you still working on it?

**Comment by chashmeetsingh** [comment]
Closing this because of inactivity. Feel free to open another PR.

**Pull request closed without merging**
