### PR TITLE
Chore: setting keys

### PR DESCRIPTION
**Pull request by chashmeetsingh**
Fixes issue #199 

Changes:
- update keys for settings

Screenshots for the change: 
n/a

### CODE REVIEW

**Comment by chashmeetsingh** [comment]
please review @dynamitechetan @chiragw15 @isuruAb @amitiwary999 @betterclever

**Comment by chiragw15** [comment]
@chashmeetsingh What are the keys decided finally? I guess Android app uses different keys than IOS. Can you document the final keys decided please. We will then change according to that.

**Comment by amitiwary999** [comment]
@chiragw15 I have changed the keys in current pr.

**Comment by chashmeetsingh** [comment]
Refer: https://github.com/fossasia/accounts.susi.ai/issues/125#issuecomment-320579605

**Pull request merged**
