### PR TITLE
feat: add realm db support, new models, rss & websearch UI added, looping through actions added

### PR DESCRIPTION
**Pull request by chashmeetsingh**
Fixes issue #47 #95 #88 #100 

Sent a single PR as the issues were linked and if it was a single PR would have broken functionality in the app.

Changes: 
- Added modified realm class
- Refactored classes
- Webseach and RSS UI added
- Extracted models to different classes
- Chat messages save to db now
- Saved chat messages load
- Parsed all action types present

Screenshots:

screen shot 2017-06-14 at 7 11 54 am
screen shot 2017-06-14 at 7 13 07 am

App can be tested [here](https://appetize.io/app/bngee02t60ambqz5ed3kjgfgkm?device=iphone7plus&scale=50&orientation=portrait&osVersion=10.3)

### CODE REVIEW

**Comment by isuruAb** [comment]
@chashmeetsingh  squash commits

**Comment by chashmeetsingh** [comment]
@isuruAb it's not yet completed, still working on it. Check the `[WIP]` label in the heading 😄 
Will definitely squash after completing it.

**Comment by chashmeetsingh** [comment]
@mariobehling since the new model addition and supporting realm would break the previous functionality so I am working on the following issues simultaneously: https://github.com/fossasia/susi_iOS/issues/95 https://github.com/fossasia/susi_iOS/issues/88 https://github.com/fossasia/susi_iOS/issues/47

**Comment by chashmeetsingh** [comment]
please review @betterclever @dynamitechetan @chiragw15 @isuruAb @mayank408 @amitiwary999 
@uday96 @DravitLochan @mariobehling @Orbiter 

Commits are not squashed as each commit is different from others and solve different issues.

**Comment by chashmeetsingh** [comment]
App can be tested [here](https://appetize.io/app/bngee02t60ambqz5ed3kjgfgkm?device=iphone5s&scale=75&orientation=portrait&osVersion=9.3)

**Pull request merged**
