### PR TITLE
Allowing user to post skill feedback

### LINKED ISSUE #339: Implement feedback system
**Actual Behaviour**

Currently, the user can only rate a skill. We do not get a detailed feedback from the user as to where the real problem is.

**Expected Behaviour**

There is a need to implement the feedback system (new APIs have been made on the server) in our app to allow the user to submit a subjective feedback so that we can understand where we need to improve and then we can act accordingly to enhance the existing skills.
- [x] Allow the user to post skill feedback
- [x] Display skill feedback

**Screenshots of the issue**
N/A
Corresponding Susi Android issue:- https://github.com/fossasia/susi_android/issues/1388

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by imjog**
Fixes #339 

Changes: implemented post feedback feature
- Allow the user to post the skill feedback
- Handle case when the user is not logged-in
- Handle case when the skill is not rated
- Handle keyboard and textfield carefully

See **Video Demonstration** here:  https://drive.google.com/open?id=1QIyKpnnD7_QUSiFrYkhmimzFpypezSQE

### CODE REVIEW

**Comment by imjog** [comment]
@SIMRAN1 This PR is allowing the user to post the skill feedback. Displaying the skill feedback will be implemented in following PR.

**Comment by chashmeetsingh** [comment]
@imjog why not show text like: `Thank you for your feedback`?
Also, shouldn't anonymous users be able to submit feedback as well?

**Comment by imjog** [comment]
@chashmeetsingh I used the same message coming from server side after successfully feedback submission. Should I change to `Thank you for your feedback`?, looks good to me.
An anonymous user cannot submit feedback because our server-side only allows a logged-in user. We have to send `accessToken` in order to submit feedback. Allowing an anonymous user to submit feedback will lead to a lot of spam reviews.

**Comment by chashmeetsingh** [comment]
@imjog Actually, I meant to display that message in place of the feed back text field. 
@Orbiter @mariobehling  should we have anonymous feedbacks as well?

**Comment by imjog** [comment]
@chashmeetsingh We are keeping text field after feedback submission so that user can update the skill feedback. Should I remove it and display label?

**Pull request merged**
