### PR TITLE
Feat: remove standard server button

### PR DESCRIPTION
**Pull request by chashmeetsingh**
Fixes issue #189 

Changes: 
- removed standard server buttons from login, signup and forgot password
- fixed validator

Screenshots for the change: 
screen shot 2017-08-03 at 8 38 36 am
screen shot 2017-08-03 at 8 38 39 am

### CODE REVIEW

**Comment by chashmeetsingh** [comment]
please review @dynamitechetan @chiragw15 @isuruAb @amitiwary999 @betterclever

**Comment by chashmeetsingh** [comment]
done @chiragw15

**Comment by mariobehling** [comment]
28859946-fbdf601e-7777-11e7-91c0-f6518b4e6a1f

Once the box is ticked, show a field in the same area, where the user can put in a URL.

**Comment by chashmeetsingh** [comment]
Sure.

**Comment by chashmeetsingh** [comment]
done, please review. Thanks! @mariobehling

**Comment by mariobehling** [comment]
Thank you.

**Pull request merged**
