### PR TITLE
fix #101: add time stamp for messages

### LINKED ISSUE #101: Add time stamps in message UI
**Actual Behaviour**

No time stamps are present in the UI.

**Expected Behaviour**

Time stamps should be present for each message.

**Would you like to work on the issue?**

Yes.

### PR DESCRIPTION
**Pull request by chashmeetsingh**
Fixes issue #101 

Changes: 
- Added timestamp label
- Formatted date to show in "HH:mm a" format: "17:48 PM"

Screenshots for the change: 
screen shot 2017-06-16 at 2 26 05 pm
screen shot 2017-06-16 at 2 25 56 pm

### CODE REVIEW

**Comment by chashmeetsingh** [comment]
please review @betterclever @dynamitechetan @chiragw15 @isuruAb @mayank408 @amitiwary999

**Comment by rishiraj824** [comment]
@chashmeetsingh A little bit of bottom space for the time stamp shall make it look better.

**Comment by chashmeetsingh** [comment]
done @rishiraj824

**Comment by chiragw15** [comment]
@chashmeetsingh can you post new screenshots, please?

**Pull request merged**
