### PR TITLE
 Fixes: #206 - splash screen added

### PR DESCRIPTION
**Pull request by KasunApplications**
Splash added #206 

Screenshots for the change: 
screen shot 2017-08-13 at 5 43 57 pm

### CODE REVIEW

**Comment by chashmeetsingh** [comment]
Hi, since the dark theme was taken out, can you change the colors as below:
- background: #f7f7f7
- image tint: #4284f3
- label textColor: black

**Comment by KasunApplications** [comment]
Hi @chashmeetsingh, Done requested changes.
screen shot 2017-08-13 at 9 28 38 pm

**Comment by chashmeetsingh** [comment]
@KasunApplications please squash your commits.

**Comment by mariobehling** [comment]
Please take out "Copyright notice". No need here.

**Comment by KasunApplications** [comment]
Copy right notice removed.

screen shot 2017-08-14 at 8 33 13 am

**Pull request merged**
