### PR TITLE
feat: change theme support, redesigned UI, refactored Settings Controller

### PR DESCRIPTION
**Pull request by chashmeetsingh**
Fixes issue #124 

Changes: 
- light theme for chat added
- fixed tests
- updated settings controller
- redesigned UI

Screenshots for the change: 
screen shot 2017-07-31 at 2 51 57 am
screen shot 2017-07-31 at 2 52 01 am
screen shot 2017-07-31 at 2 52 04 am
screen shot 2017-07-31 at 2 52 23 am
screen shot 2017-07-31 at 2 52 25 am
screen shot 2017-07-31 at 2 52 29 am
screen shot 2017-07-31 at 2 53 34 am
screen shot 2017-07-31 at 2 54 07 am

### CODE REVIEW

**Comment by betterclever** [comment]
@chashmeetsingh Looks great. The black app bar in the forgot password activity though looks a bit odd compared to the rest of the UI. Some other color should be chosen I think.

**Comment by chiragw15** [comment]
Also keep background color of login screen, signup and forgot password screen same. If I am not wrong, background color of login screen looks a little different to me than other two.

**Comment by chashmeetsingh** [comment]
@betterclever yes, will make that black color transparent.
@chiragw15 will check that again.

**Comment by chashmeetsingh** [comment]
screen shot 2017-07-29 at 5 04 22 pm
screen shot 2017-07-29 at 5 04 26 pm

**Comment by betterclever** [comment]
@chashmeetsingh The current revision looks a lot better. :+1: You may also try switching the bottom typing bar to something like google assistant. I do not mean with a dominant mic button, but a rectangular persitant bottom bar rather than rounded one.

**Comment by chashmeetsingh** [comment]
Yes, that's the next step I am currently working on 👍

**Comment by chashmeetsingh** [comment]
please review @dynamitechetan @chiragw15 @isuruAb @mayank408 @amitiwary999 @betterclever

**Pull request merged**
