### PR TITLE
feat: added setting button on chat screen

### PR DESCRIPTION
**Pull request by imjog**
**Fixes** #278 

**Changes:** 
- Added a button on the chat screen to go directly to settings screen from chat screen
- Added **UI tests** for settings button

**Screenshots for the change:** 
<table>
<tr>
<td></td>
<td></td>
<tr>
</table>

### CODE REVIEW

**Comment by imjog** [comment]
@mariobehling @chashmeetsingh @SIMRAN1 @baquer @arundhati24 @batbrain7 Please review the PR.

**Comment by imjog** [comment]
@SIMRAN1 I followed the material design which is our whole app is using.

**Comment by SIMRAN1** [comment]
ok @imjog !

**Comment by imjog** [comment]
@arundhati24 I planned for the same. I thought of adding Login, Settings, and Susi skills button in one expandable button. But for now, I added this.

**Pull request merged**
