### PR TITLE
Keyboard observers + Map view added

### PR DESCRIPTION
**Pull request by chashmeetsingh**
- Few fixes
- Added map View

screen shot 2017-03-21 at 4 52 31 pm

- Add link previews for web search results

screen shot 2017-03-21 at 4 52 31 pm

### CODE REVIEW

**Comment by chashmeetsingh** [comment]
@niranjan94 @mariobehling can this be merged?

**Comment by niranjan94** [comment]
@chashmeetsingh when I build this locally and run, I get the following error for signup

```
http://api.asksusi.com/aaa/signup.json
["signup": niranjan12@example.com, "password": xyzzy]
400
Could not parse the data as JSON: '344 bytes'
```

**Comment by chashmeetsingh** [comment]
Will take a look as soon as I can :smile:

**Comment by chashmeetsingh** [comment]
@niranjan94 fixed the register, web search needs to be fixed 😄 .
Also if possible you can give suggestions on the error string for register view to have one uppercase, lower and a numeral, currently it looks too long.
Thanks!

**Pull request merged**
