### PR TITLE
feat: setup instructions, move screenshots

### LINKED ISSUE #24: Add project details and setup instructions for devs to Readme.md
The Readme.md only has some screenshots at the moment. Please add info following other FOSSASIA projects.

### PR DESCRIPTION
**Pull request by chashmeetsingh**
Fixes #24 
- Move screenshots to /docs/img
- Add Project setup details

### CODE REVIEW

**Comment by mariobehling** [comment]
Please help by following the descriptions in issues. Move the screenshots to /docs/img/

**Comment by chashmeetsingh** [comment]
I verified with susi_android repo it was named `screenshots` but in open-event it was under `img`, will make it `img` then.

**Comment by mariobehling** [comment]
Please avoid spaces in names.

**Comment by chashmeetsingh** [comment]
Hey can you please point me to what you are referring to?

**Comment by mariobehling** [comment]
Screen 1.png -> Screen1.png

**Comment by chashmeetsingh** [comment]
Ok will fix in a moment.

**Comment by mariobehling** [comment]
Please help to resolve merge conflicts.

**Pull request closed without merging**
