### PR TITLE
Fix: Change buttons color

### LINKED ISSUE #491: Home screen signup skip forget password button is not readable
**Actual Behaviour**

forget password, skip and signup button color is not readable

**Expected Behaviour**

all should be white in color so that they are readable

**Would you like to work on the issue?**
Yes working on it.

### PR DESCRIPTION
**Pull request by baquer**
Fixes #491 

Changes: Change color of buttons from blue to white

Screenshots for the change: 

screenshot 2019-02-28 at 9 46 41 pm

### CODE REVIEW

**Comment by baquer** [comment]
@chashmeetsingh , @jogendra  , please review the PR.

**Comment by chashmeetsingh** [comment]
Not sure about this. It was based on the theme blue and white. IMO it doesn't look good.

**Comment by jogendra** [comment]
@chashmeetsingh actually the issue is the buttons titles is not readable (they looks faded)

**Comment by chashmeetsingh** [comment]
Oh, ok. @baquer please resolve the conflicts.

**Comment by baquer** [comment]
> Oh, ok. @baquer please resolve the conflicts.
@chashmeetsingh , done

**Pull request merged**
