### PR TITLE
feat: option to switch between standard and custom server

### PR DESCRIPTION
**Pull request by chashmeetsingh**
Fixes issue #72: option to choose between custom and standard server

Changes: 
- Added radio buttons for toggling 
- Saved the URL in UserDefaults which can be used for making API calls

Screenshots for the change: 

screen shot 2017-06-09 at 5 10 47 pm

screen shot 2017-06-09 at 7 13 28 pm

### CODE REVIEW

**Comment by chashmeetsingh** [comment]
please review @betterclever @dynamitechetan @chiragw15 @isuruAb @ishaan1995 @thePsguy

**Comment by chiragw15** [comment]
@chashmeetsingh Did you do this for signup and forgot password too?

**Comment by chashmeetsingh** [comment]
Skipped my mind, on it.

**Comment by chashmeetsingh** [comment]
done @chiragw15

**Pull request merged**
