### PR TITLE
fix: show thumbnail images when video played

### PR DESCRIPTION
**Pull request by chashmeetsingh**
Fixes issue #85: no message added when video is played

Changes: 
- Added a thumbnail image

Screenshots for the change: 

image

### CODE REVIEW

**Comment by mariobehling** [comment]
To confirm: Is the action type "play video" or "play music". How do you decide if a video or only music should be played?

**Comment by mariobehling** [comment]
Please always actively ask co-developers in all PRs to review your PRs using the "@" feature and ping them if necessary later on chat.

**Comment by chashmeetsingh** [comment]
Currently, I am checking the query input by the user and checking if `play` is present in it then searching for a video with the query using youtube data API and displaying results. Currently, this action type is not supported by the server and when it does the client side would require 5-10 LOC being changed.

**Comment by chashmeetsingh** [comment]
please review @betterclever @dynamitechetan @chiragw15 @isuruAb @ishaan1995 @thePsguy

**Comment by mariobehling** [comment]
Currently, I am checking the query input by the user and checking if play is present in it then searching for a video with the query using youtube data API and displaying results. Currently, this action type is not supported by the server

@chashmeetsingh 

By doing this you are diverting from the project settings. This kind of out of scope solution will make it very difficult to debug across clients in future and it should never be implemented in that way. If you want to see an action type "video" it needs to be defined in the server. In your example it is also not clear if the user wants an audio or video to be played. All logic and action types come from the server. 

Please be entirely clear, that this is not how SUSI is supposed to work.

The "intelligence" - logic and action types must come from the server. The chat should look the same on all clients and the easiest way to ensure this consistency is - if the server determines the actions.

Please ensure that you have followed this approach across the iOS project. Don't invent your own action types and output! Only do what the SUSI server puts out.

> 5-10 LOC being changed.

What is LOC?

**Comment by mariobehling** [comment]
Use the SUSI servers logic and action types only. Open an issue in the server, if there is an action type that you don't see covered yet.

Don't make up your own action types client-side!

**Comment by mariobehling** [comment]
Follow the Servers logic only!

The clients need to follow the servers logic.

**Comment by chashmeetsingh** [comment]
Ok, sure. I was trying to replicate the functionality currently present in the Android app and used the same logic as was used there. Will surely add an issue for the same there on the server repo.

`LOC -> Lines of Code`

**Comment by chashmeetsingh** [comment]
Issue https://github.com/fossasia/susi_server/issues/252 created.

**Comment by mariobehling** [comment]
> Ok, sure. I was trying to replicate the functionality currently present in the Android app

Yes, exactly. That is not how it is supposed to work. Please open an issue in the Android issue tracker. Please also help to get this kind of code out.

The background is this: All information, logic and action types must come from the server. Actions must be defined by the server not by a client. Compare this to a Facebook messenger for example, it would not make sense, if a user could only see the history of the web client and not on the Android client. And all media is displayed in the same way across different clients. Please ensure that you relay to the server for all functions and features. Use the history that is stored on the server! All clients should show the same history and perform the same kind of actions.

**Comment by chashmeetsingh** [comment]
Yes, makes sense 👍

**Comment by chashmeetsingh** [comment]
Created issue on android repo: https://github.com/fossasia/susi_android/issues/670

**Comment by chashmeetsingh** [comment]
Closing this issue for now.

**Pull request closed without merging**
