### PR TITLE
Displaying 5-Star ratings data from server

### LINKED ISSUE #332: Display 5-Star ratings data from server
**Actual Behaviour**

Currently, 5-star rating data is hard-coded.

**Expected Behaviour**

Display data on labels from the server using `getSkillRatings` API.

**Screenshots of the issue**

N/A

**Would you like to work on the issue?**

Yes

### PR DESCRIPTION
**Pull request by imjog**
Fixes #332 

Changes: Displaying 5-Star ratings data from server

Screenshots for the change: 
<table>
<tr>
<td>Skill with ratings</td>
<td>Skill without rating</td>
</tr>
<tr>
<td>

</td>
<td>

</td></tr>
</table>

### CODE REVIEW

**Comment by imjog** [comment]
@chashmeetsingh @arundhati24 @batbrain7 @Akshat-Jain @akshatnitd  @SIMRAN1 Please review PR

**Comment by imjog** [comment]
@arundhati24 Yes, it is intentional. I don't think it should be same as rest of the background!

**Comment by arundhati24** [comment]
@imjog I didn't point out the white background, but the empty space next to the 'Acronyms of NASA' in that section. It is not present in any other section. It's okay if that is intentional. :)

**Comment by imjog** [comment]
@arundhati24 It is because here only one example. Space is being utilizes when there is more than one examples for skills, eg.
simulator screen shot - iphone x - 2018-06-13 at 12 52 50

**Comment by arundhati24** [comment]
Please see the highlighted area. This is not being done for other sections like Content Type etc. And, this becomes apparent for skills where there is empty space. Appears a bit odd to me. But, as I am unaware of the iOS guidelines, please consider what is appropriate to do. :)

edit

**Pull request merged**
