### PR TITLE
Add ability to play youtube videos

### PR DESCRIPTION
**Pull request by chashmeetsingh**
Fixes https://github.com/fossasia/susi_iOS/issues/61 : Use Youtube API to play videos

youtube-integration 1

### CODE REVIEW

**Comment by chashmeetsingh** [comment]
added @isuruAb

**Comment by chashmeetsingh** [comment]
done 👍

**Comment by mariobehling** [comment]
Which issue is this related to?

Please follow best practices.

**Comment by chashmeetsingh** [comment]
Updated description

**Pull request merged**
