### PR TITLE
Fixes #42: adds the Launch Screen UI 

### LINKED ISSUE #42: Add the Launch Screen UI
Currently the `LaunchScreen.storyboard` is an empty view. Populate it with the same `UIColor` as in the app with the logo in the middle.

Also, to provide a better UI/UX experience add an animation where the logo in the middle animates to the top and then the text fields appear.

### PR DESCRIPTION
**Pull request by chashmeetsingh**
Adds the LaunchScreen UI

### CODE REVIEW

**Comment by mariobehling** [comment]
No delay, please. Don't make people wait for no reason.

**Comment by mariobehling** [comment]
Let's not add fancy effects actually. We need the app to work feature-wise. Are you able to generate diagrams and tables from JSON already? Please explore these kind of features. The main goal is to make this app seem invisible in future.

**Comment by chashmeetsingh** [comment]
Ok sure! Let me close this PR then. What diagram and table generation are you referring to? Please elaborate a bit.
Thanks!

**Comment by mariobehling** [comment]
> What diagram and table generation are you referring to? Please elaborate a bit.

Please do learn more about the server and follow up there. Please learn more about the server and how the JSON results work. It would be a bit too easy, if you drop all your questions on me simply. It is your job understanding how the server works and provides answers. Thanks.

> Let me remove the animation and instead only have the initial screen with the logo in the middle, followed by the login screen?

Yes, please.

**Comment by chashmeetsingh** [comment]
Sure!

**Pull request merged**
