### PR TITLE
Update SignUpVCMethods.swift

### PR DESCRIPTION
**Pull request by baquer**
check

### CODE REVIEW

**Comment by chashmeetsingh** [comment]
@baquer please describe what changes were made to the code and the reason for the same. Also, it's better to open an issue first and then start working on it.
Thanks!

**Comment by baquer** [comment]
I just update the password fields by adding lines in which our first letter of our password string should be capital and I used capitalised for this.

**Comment by chashmeetsingh** [comment]
Shouldn't that be checking if not capitalized then show the toast error?

**Comment by baquer** [comment]
no I didn't check that

**Comment by chashmeetsingh** [comment]
Closing due to inactivity. Feel free to open another PR.

**Pull request closed without merging**
